-- 코드를 작성해주세요
SELECT s.ID AS ID
FROM ECOLI_DATA AS e
INNER JOIN (SELECT f.ID AS ID, e.PARENT_ID AS PARENT_ID
FROM ECOLI_DATA AS e
INNER JOIN (SELECT ID, PARENT_ID
FROM ECOLI_DATA
WHERE PARENT_ID IS NOT NULL) AS f
ON e.ID = f.PARENT_ID
WHERE e.PARENT_ID IS NOT NULL) AS s
ON e.ID = s.PARENT_ID
WHERE e.PARENT_ID IS NULL
ORDER BY ID ASC;