-- 코드를 작성해주세요
SELECT i.ITEM_ID AS ITEM_ID,
i.ITEM_NAME AS ITEM_NAME,
i.RARITY AS RARITY
FROM ITEM_INFO AS i
LEFT JOIN ITEM_TREE AS t
ON i.ITEM_ID = t.PARENT_ITEM_ID
WHERE t.ITEM_ID IS NULL
ORDER BY i.ITEM_ID DESC;