-- 코드를 입력하세요
SELECT p.PRODUCT_CODE AS PRODUCT_CODE,
SUM(o.SALES_AMOUNT * p.PRICE) AS SALES
FROM OFFLINE_SALE AS o
LEFT JOIN PRODUCT AS p 
ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;

# SELECT p.PRODUCT_CODE AS PRODUCT_CODE,
# o.SALES_AMOUNT * p.PRICE
# FROM OFFLINE_SALE AS o
# LEFT JOIN PRODUCT AS p 
# ON p.PRODUCT_ID = o.PRODUCT_ID;