-- 코드를 입력하세요
SELECT r.FOOD_TYPE AS FOOD_TYPE,
r.REST_ID AS REST_ID, 
r.REST_NAME AS REST_NAME,  
r.FAVORITES AS FAVORITES
FROM
(SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE) AS s
LEFT JOIN REST_INFO AS r
ON s.FOOD_TYPE = r.FOOD_TYPE AND s.FAVORITES = r.FAVORITES
ORDER BY r.FOOD_TYPE DESC;
