-- 코드를 작성해주세요
SELECT i.ID AS ID,
CASE
WHEN i.RANKING / t.TOTAL <= 0.25 THEN 'CRITICAL'
WHEN i.RANKING / t.TOTAL <= 0.5 THEN 'HIGH'
WHEN i.RANKING / t.TOTAL <= 0.75 THEN 'MEDIUM'
ELSE 'LOW'
END AS COLONY_NAME
FROM (SELECT ID, ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANKING
FROM ECOLI_DATA) AS i, 
(SELECT COUNT(ID) AS TOTAL FROM ECOLI_DATA) AS t
ORDER BY ID ASC;
