-- 코드를 입력하세요
SELECT u.USER_ID USER_ID, 
u.NICKNAME NICKNAME,
CONCAT(u.CITY,' ', u.STREET_ADDRESS1 ,' ' ,u.STREET_ADDRESS2) 전체주소,
CONCAT(SUBSTRING(u.TLNO,1,3), '-',SUBSTRING(u.TLNO,4,4),'-',SUBSTRING(u.TLNO,8)) 전화번호
FROM (SELECT WRITER_ID, COUNT(BOARD_ID) CNT
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID) c
LEFT JOIN USED_GOODS_USER u
ON c.WRITER_ID = u.USER_ID
WHERE c.CNT >= 3
ORDER BY USER_ID DESC;
