-- 코드를 입력하세요
SELECT
info.REST_ID as REST_ID, 
info.REST_NAME as REST_NAME, 
info.FOOD_TYPE as FOOD_TYPE, 
info.FAVORITES as FAVORITES,
info.ADDRESS as ADDRESS,
review.SCORE as SCORE
FROM REST_INFO as info
inner join
(SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) as SCORE
FROM REST_REVIEW
GROUP BY REST_ID) as review
on info.REST_ID = review.REST_ID
WHERE LEFT(info.ADDRESS , 2) = '서울'
ORDER BY SCORE DESC, FAVORITES DESC;
