-- 코드를 작성해주세요


SELECT i.FISH_COUNT AS FISH_COUNT,
n.FISH_NAME AS FISH_NAME
FROM (SELECT FISH_TYPE,
COUNT(ID) AS FISH_COUNT
FROM FISH_INFO
GROUP BY FISH_TYPE) AS i
LEFT JOIN FISH_NAME_INFO AS n
ON i.FISH_TYPE = n.FISH_TYPE
ORDER BY FISH_COUNT DESC;