-- 코드를 입력하세요
SELECT
CAR_ID,
CASE 
WHEN (SUM(CASE 
      WHEN(DATE('2022-10-16') BETWEEN DATE(START_DATE) AND DATE(END_DATE))THEN 1 ELSE 0 
      END)) > 0 THEN '대여중' ELSE '대여 가능'
      END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;

# SELECT CAR_ID, START_DATE,
# END_DATE, 
# CASE 
# WHEN(SUM 
#      (CASE 
#       WHEN(DATE('2022-10-16') BETWEEN DATE(START_DATE) AND DATE(END_DATE))THEN 1 ELSE 0 END)) > 0 
#      THEN '대여 중' 
#      ELSE'대여 가능' 
#      END AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# GROUP BY CAR_ID
# ORDER BY CAR_ID DESC;



