-- 코드를 입력하세요
SELECT t.PRODUCT_ID PRODUCT_ID,
p.PRODUCT_NAME PRODUCT_NAME,
t.TOTAL_AMOUNT * p.PRICE TOTAL_SALES
FROM (SELECT PRODUCT_ID, SUM(AMOUNT) TOTAL_AMOUNT
FROM FOOD_ORDER o
WHERE o.PRODUCE_DATE LIKE "2022-05%"
GROUP BY PRODUCT_ID) t
JOIN FOOD_PRODUCT p
ON t.PRODUCT_ID = p.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;