-- 코드를 입력하세요
SELECT b.WRITER_ID AS USER_ID,
u.NICKNAME AS NICKNAME,
b.TOTAL AS TOTAL_SALES
FROM (SELECT WRITER_ID, SUM(PRICE) AS TOTAL
FROM USED_GOODS_BOARD
WHERE STATUS = "DONE"
GROUP BY WRITER_ID) AS b
LEFT JOIN USED_GOODS_USER AS u
ON b.WRITER_ID = u.USER_ID
WHERE b.TOTAL >= 700000
ORDER BY b.TOTAL ASC;