-- 코드를 작성해주세요
SELECT 
infos.ITEM_ID AS ITEM_ID,
infos.ITEM_NAME AS ITEM_NAME,
infos.RARITY AS RARITY
FROM (SELECT t.ITEM_ID AS ID
FROM (SELECT ITEM_ID
FROM ITEM_INFO
WHERE RARITY = 'RARE') AS r
INNER JOIN ITEM_TREE AS t ON t.PARENT_ITEM_ID = r.ITEM_ID) AS items
INNER JOIN ITEM_INFO AS infos ON items.ID = infos.ITEM_ID
ORDER BY ITEM_ID DESC;