-- 코드를 작성해주세요
SELECT 
e.ID AS ID,
e.GENOTYPE AS GENOTYPE,
g.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS e
INNER JOIN 
(SELECT ID, GENOTYPE
FROM ECOLI_DATA) AS g
ON e.PARENT_ID = g.ID
WHERE
e.GENOTYPE & g.GENOTYPE = g.GENOTYPE
ORDER BY e.ID ASC;