-- 코드를 입력하세요

SELECT MONTH(START_DATE) AS MONTH,
CAR_ID,
COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE (START_DATE BETWEEN '2022-08-01' AND '2022-10-31') AND
CAR_ID IN
(SELECT CAR_ID
FROM(SELECT CAR_ID, COUNT(HISTORY_ID) AS CNT, START_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE (START_DATE BETWEEN '2022-08-01' AND '2022-10-31')
GROUP BY CAR_ID) as c
WHERE CNT >= 5)
GROUP BY MONTH, CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;