-- 코드를 작성해주세요
SELECT
DISTINCT(D.ID) AS ID,
D.EMAIL AS EMAIL,
D.FIRST_NAME AS FIRST_NAME,
D.LAST_NAME AS LAST_NAME
FROM DEVELOPERS AS D
INNER JOIN
(SELECT CODE
FROM SKILLCODES
WHERE NAME = 'Python' OR NAME = 'C#') AS S
ON D.SKILL_CODE & S.CODE = S.CODE
ORDER BY D.ID ASC;