-- 코드를 작성해주세요
SELECT YEAR(e.DIFFERENTIATION_DATE) AS YEAR,
m.MAX_SIZE - e.SIZE_OF_COLONY AS YEAR_DEV,
e.ID
FROM ECOLI_DATA AS e LEFT JOIN 
(SELECT YEAR(DIFFERENTIATION_DATE) AS MAIN_YEAR,
MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA
GROUP BY MAIN_YEAR) AS m
ON m.MAIN_YEAR = YEAR(e.DIFFERENTIATION_DATE)
ORDER BY YEAR ASC, YEAR_DEV ASC;