-- 코드를 작성해주세요
SELECT m.ID AS ID,
n.FISH_NAME AS FISH_NAME,
m.LENGTH AS LENGTH
FROM
(SELECT i.ID AS ID,
i.FISH_TYPE AS FISH_TYPE,
i.LENGTH AS LENGTH
FROM FISH_INFO AS i,
(SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
FROM FISH_INFO
GROUP BY FISH_TYPE) AS t
WHERE i.FISH_TYPE = t.FISH_TYPE AND i.LENGTH = t.LENGTH) AS m
LEFT JOIN FISH_NAME_INFO AS n
ON m.FISH_TYPE = n.FISH_TYPE;


# SELECT i.ID AS ID,
# n.FISH_NAME AS FISH_NAME,
# MAX(LENGTH) AS LENGTH
# FROM FISH_INFO AS i
# INNER JOIN FISH_NAME_INFO AS n
# ON i.FISH_TYPE = n.FISH_TYPE)
# GROUP BY i.FISH_TYPE;