-- 코드를 작성해주세요
SELECT s.TOTAL AS SCORE,
s.EMP_NO AS EMP_NO,
e.EMP_NAME AS EMP_NAME,
e.POSITION AS POSITION,
e.EMAIL AS EMAIL
FROM (SELECT EMP_NO,
SUM(SCORE) AS TOTAL
FROM HR_GRADE
WHERE YEAR = 2022
GROUP BY EMP_NO
ORDER BY TOTAL DESC
LIMIT 1) AS s
LEFT JOIN HR_EMPLOYEES AS e
ON e.EMP_NO = s.EMP_NO;
