-- 코드를 입력하세요
SELECT 
board.TITLE as TITLE, 
board.BOARD_ID as BOARD_ID, 
reply.REPLY_ID as REPLY_ID, 
reply.WRITER_ID as WRITER_ID, 
reply.CONTENTS as CONTENTS, 
DATE_FORMAT(reply.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as board
INNER JOIN USED_GOODS_REPLY as reply ON board.BOARD_ID = reply.BOARD_ID
WHERE YEAR(board.CREATED_DATE) = 2022 AND MONTH(board.CREATED_DATE) = 10
ORDER BY CREATED_DATE ASC, TITLE ASC