-- 코드를 작성해주세요
SELECT a.DEPT_ID DEPT_ID,
d.DEPT_NAME_EN DEPT_NAME_EN,
a.AVG_SAL AVG_SAL
FROM(SELECT DEPT_ID, ROUND(AVG(SAL), 0) AVG_SAL
FROM HR_EMPLOYEES
GROUP BY DEPT_ID) a
JOIN HR_DEPARTMENT d
ON a.DEPT_ID= d.DEPT_ID
ORDER BY AVG_SAL DESC;