-- 코드를 입력하세요
SELECT b.CATEGORY AS CATEGORY,
SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES AS s
LEFT JOIN BOOK AS b
ON s.BOOK_ID = b.BOOK_ID
WHERE s.SALES_DATE LIKE "2022-01%"
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY ASC;