-- 코드를 입력하세요
SELECT f.CATEGORY CATEGORY, m.MAX_PRICE MAX_PRICE, f.PRODUCT_NAME PRODUCT_NAME
FROM (SELECT CATEGORY, MAX(PRICE) MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치','식용유')
GROUP BY CATEGORY) m
LEFT JOIN FOOD_PRODUCT f
ON m.CATEGORY = f.CATEGORY AND m.MAX_PRICE = f.PRICE
ORDER BY MAX_PRICE DESC;
