-- 코드를 입력하세요
SELECT 
b.BOOK_ID AS BOOK_ID,
a.AUTHOR_NAME AS AUTHOR_NAME,
DATE_FORMAT(b.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK AS b
LEFT JOIN AUTHOR AS a
ON a.AUTHOR_ID = b.AUTHOR_ID
WHERE b.CATEGORY = '경제'
ORDER BY b.PUBLISHED_DATE ASC;